### ISSUE TITLE
Scope down IAM policies in templates/iam.py

### ISSUE THREAD

**Issue by lizroth** [awslabs/pipeformer#24]
From the `TODO` here: https://github.com/awslabs/pipeformer/pull/13/files#diff-d27d002e8b30320ac43519019059850fR59

> `TODO`: Figure out how to scope this down without breaking IAM. IAM policies break if there is a `*` in certain fields, so this does not work: `arn:PARTITION:*:REGION:ACCOUNT:*`

**Comment by mattsb42-aws** [comment]
Closing down project: #52
