### ISSUE TITLE
Change principal for KMS admin policy

### ISSUE THREAD

**Issue by lizroth** [awslabs/pipeformer#26]
From TODO in https://github.com/awslabs/pipeformer/pull/19/files#diff-bce5ff32dafb66cc659fd0d41a06d23eR51

Change the `Principal` in the policy in `internal/templates/core.py` for KMS admin operations (e.g. `PutKeyPolicy`) to something other than `root`

**Comment by mattsb42-aws** [comment]
Closing down project: #52
