### ISSUE TITLE
No matching distribution found for pipeformer

### ISSUE THREAD

**Issue by charles545587** [awslabs/pipeformer#4]
When trying to install using pip install pipeformer as per the README generates the following error.

No matching distribution found for pipeformer

A search of https://pypi.org/ also does not show a package called pipeformer.

**Comment by mattsb42-aws** [comment]
Hi @charles545587, thanks for your interest!

Pipeformer is actually a brand new project that we are just starting work on. Aside from the docs that are up now, I have an initial MVP almost ready for review. There should be a PR coming in for that this week.

Also, thanks for the bug on pypi. I've parked the name now and it will show you a placeholder message if you try to install it.
