### ISSUE TITLE
Pipeformer builds itself

### ISSUE THREAD

**Issue by karlw00t** [awslabs/pipeformer#47]
This is defining how a pipeformer config file should exists in a project such that it can be auto discovered. I think we can get mixed up in terminology very quickly here, so let's define the things we are talking about:

**PR Build** - These are actions that happen when a Pull Request is submitted to your project.
**Deploy Pipeline** - This is a Code Pipeline that builds a project and releases the project. "Release" is intentionally vague here.
**Infrastructure Pipeline** - This is a Code Pipeline that deploys the above resources. It watches master, builds and deploys the CloudFormation template(s) needed for the project PR Builds and/or Deploy Pipelines.

We should allow people to create and deploy PR Builds and Deploy Pipelines from the CLI, but we should also allow people to create a Infrastructure Pipeline that will build and deploy their PR Builds and Deploy Pipelines.  At a high level:

1/ user would define a .pipeformer.yml file in the project's root
2/ User would run `pipeformer infrastructure` with the correct AWS credentials to create a Infrastructure Pipeline. This pipeline would create and connect any PR Builds or Deploy Pipelines.
3/ When changes are pushed to master, the infrastructure pipeline would run, and create any new, or delete any old, resources as defined in the config file.

The advantage here is that if you want to set up a new PR Build, you only need to update the .pipeformer.yml file and the changes roll out.

**Comment by mattsb42-aws** [comment]
Let's chat offline, but this is really out of scope for pipeformer.

I'll leave this open to remind me to add a breadcrumb for the thing that will address this later.

**Comment by mattsb42-aws** [comment]
Closing down project: #52
